Algoritmo "Idades"

Var

Nomea, Nomeb : caractere
Idadea,Idadeb : inteiro
Media : real

Inicio

Escreval("Dados da primeira pessoa:")
Escreva("Nome: ")
leia(Nomea)
Escreva("Idade: ")
leia(Idadea)
Escreval("Dados da segunda pessoa:")
Escreva("Nome: ")
leia(Nomeb)
Escreva("Idade: ")
leia(Idadeb)
Media <- (idadea+idadeb)/2
escreval("A idade média de ",Nomea," e ",Nomeb," é de ",Media:4:1," anos")

Fimalgoritmo