Algoritmo "Medidas"

Var

A, B, C, QUADRADO, TRIANGULO, TRAPEZIO : real

Inicio

Escreva("Digite a medida A: ")
leia(A)
Escreva("Digite a medida B: ")
leia(B)
Escreva("Digite a medida C: ")
leia(C)
QUADRADO <- A^2
TRIANGULO <- (A*B)/2
TRAPEZIO <- ((A+B)*C)/2
Escreval("AREA DO QUADRADO = ",QUADRADO:8:4)
Escreval("AREA DO TRIANGULO = ",TRIANGULO:8:4)
Escreval("AREA DO TRAPEZIO = ",TRAPEZIO:8:4)

Fimalgoritmo