algoritmo "pgm05"
// Função : Exibir as variaveis idade, altura e peso
// Autor : Lucas Igor A M Nogueira
// Data : 20/01/2021

var
      idade: inteiro
      altura, peso: real


inicio
      //atribuir valores aos dados
      idade <- 34
      altura <- 177.5
      peso <- 94.5

      //exibi os dados armazenados
      escreval("Idade: ",idade)
      escreval("Altura: ", altura)
      escreva("Peso: ", peso)
         
fimalgoritmo
