algoritmo "pgm15"
// Função : Armazenar um valor e exibir o sue antecessor
// Autor : Lucas Igor A M Nogueira
// Data : 21/01/2021

var

   num1: inteiro

inicio

      //solicita os dados para o usuário e armazena na memória do computador
      escreva("Digite um valor: ")
      leia(num1)
      escreval

      //exibi o resultado das operaçãoes realizadas
      escreva("O antecessor de ", num1," é: ",num1 - 1)



fimalgoritmo
