algoritmo "pgm20"
// Função : Armazenar um valor em dolar e converter para reais
// Autor : Lucas Igor A M Nogueira
// Data : 22/01/2021

var
      valor, dolar: real

inicio

      //armazena o valor informado pelo usuario
      escreva("Informe o valor em dolar a ser convertido: ")
      leia(valor)
      escreval
      
      //exibir o valor convertido
      escreva("O valor convertido em reais é de R$ ", 6.61 * valor)


fimalgoritmo
