algoritmo "pgm39"
// Função :atribui valores para a e b. Calcula e exibe para o usuario
// Autor : Lucas Igor A M Nogueira
// Data : 25/01/2021

var

   a, b: inteiro

inicio

   //atribui valor as variaveis, armazena e calcula
   a<-10
   b<-a+1
   a<-b+1
   b<-a+1

   //exibi os valores para a
   escreval(a)
   
   //atribui valor para a, armazena e calcula
   a<-b+1

   //exibe os novos valores de a e b
   escreva(a,", ",b)


fimalgoritmo
