algoritmo "pgm36"
// Função : atribui valores para a e b e exibe para o usuario
// Autor : Lucas Igor A M Nnogueira
// Data : 25/01/2021

var

   a, b: inteiro

inicio

   //atribui valor as variaveis e armazena
   a<-10
   b<-20
   
   //exibe a varivel b na tela do usuarui
   escreva(b)
   escreval
   
   //atribui novo valor para b
   B<-5
   
   //exibe os valores para a e b
   escreval(a,", ",B)


fimalgoritmo
