algoritmo "pgm41"
// Função :atribui valores para x, y e z. Calcula e exibe para o usuario
// Autor : Lucas Igor A M Nogueira
// Data : 25/01/2021

var

   x, y, z: inteiro

inicio

   //atribui valor as variaveis, armazena e calcula
   x<-1
   y<-2
   z<-y-x
   
   //exibi a variavel z
   escreval(z)
   
   //atribui novos valores as variaveis
   x<-5
   y<-x+z
   
   //exibe os valores de x, y  e z
   escreva(x,", ",y,", ",z)


fimalgoritmo
