Algoritmo "Terreno"

Var

largura, comprimento, valor, area, preco : real


Inicio

Escreva("Digite a largura do terreno: ")
leia (largura)
Escreva("Digite o comprimento do terreno: ")
leia (comprimento)
Escreva ("Digite o valor do metro quadrado: ")
leia (valor)
escreval
Area <- largura*comprimento
escreval ("Area do terreno = ", area:8:2)
escreval
preco <- area*valor
escreval ("Preco do terreno = ", preco:8:2)

Fimalgoritmo